###############################################
#API Configuration
###############################################
openapi.yaml - OpenAPI Specification for API Gateway

Create this file in the same directory as main.tf.

YAML

# openapi.yaml
swagger: "2.0"
info:
  title: Microservices API
  description: API Gateway for fan-out microservices
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
securityDefinitions:
  fusionAuthAuth:
    type: "apiKey"
    name: "Authorization"
    in: "header"
    x-google-security:
      # This points to the Cloud Function that acts as your custom authorizer
      # The function will receive the Authorization header and validate it
      # against FusionAuth.
      extensibleAuth:
        rules:
          - selector: ".*"
            backendAuth:
              protocol: "HTTP"
              uri: "${auth_function_url}"
              jwt: {} # Indicates that the function will validate a JWT
security:
  - fusionAuthAuth: []
x-google-backend:
  rules:
    # Payment Service - Pub/Sub integration
    - selector: "operations.payments"
      address: "https://pubsub.googleapis.com/v1/projects/${gcp_project_id}/topics/${payment_pubsub_topic_name}:publish"
      protocol: "grpc" # Pub/Sub API uses gRPC, but API Gateway can bridge HTTP to gRPC
      path_translation: APPEND_PATH_TO_ADDRESS
      deadline: 30.0
      authentication:
        jwt_audience: "https://pubsub.googleapis.com/" # Audience for Pub/Sub service account JWT
    # Telemedicine Service - Pub/Sub integration
    - selector: "operations.telemedicine"
      address: "https://pubsub.googleapis.com/v1/projects/${gcp_project_id}/topics/${telemedicine_pubsub_topic_name}:publish"
      protocol: "grpc"
      path_translation: APPEND_PATH_TO_ADDRESS
      deadline: 30.0
      authentication:
        jwt_audience: "https://pubsub.googleapis.com/"
    # Pharmacy Service - Load Balancer integration (GKE)
    - selector: "operations.pharmacy"
      address: "http://${pharmacy_alb_ip}" # Target the Load Balancer IP
      protocol: "http/1.1"
      path_translation: APPEND_PATH_TO_ADDRESS
      deadline: 60.0
    # Personal Health Management Service - Load Balancer integration (Compute Engine)
    - selector: "operations.personalHealthManagement"
      address: "http://${pfm_alb_ip}" # Target the Load Balancer IP
      protocol: "http/1.1"
      path_translation: APPEND_PATH_TO_ADDRESS
      deadline: 60.0
paths:
  /payments/{proxy+}:
    post:
      summary: Send payment request
      operationId: payments
      x-google-backend:
        path_translation: APPEND_PATH_TO_ADDRESS # Pass the full path to the backend
      parameters:
        - name: proxy
          in: path
          description: "Payment path"
          required: true
          type: string
      responses:
        200:
          description: Payment request accepted
        401:
          description: Unauthorized
        429:
          description: Too Many Requests
      x-google-api-key:
        # Rate limiting configuration for this path
        # This is a basic example, more granular control might be needed
        # Quota for this operation (requests per minute)
        metrics:
          - name: "payments-requests"
            value: 1
        quotas:
          - metric: "payments-requests"
            limits:
              - unit: "1/min"
                value: 100 # 100 requests per minute
  /telemedicine/{proxy+}:
    post:
      summary: Send telemedicine request
      operationId: telemedicine
      x-google-backend:
        path_translation: APPEND_PATH_TO_ADDRESS
      parameters:
        - name: proxy
          in: path
          description: "Telemedicine path"
          required: true
          type: string
      responses:
        200:
          description: Telemedicine request accepted
        401:
          description: Unauthorized
        429:
          description: Too Many Requests
      x-google-api-key:
        metrics:
          - name: "telemedicine-requests"
            value: 1
        quotas:
          - metric: "telemedicine-requests"
            limits:
              - unit: "1/min"
                value: 50
  /pharmacy/{proxy+}:
    x-google-backend:
      path_translation: APPEND_PATH_TO_ADDRESS
    get:
      summary: Get pharmacy services
      operationId: pharmacy
      parameters:
        - name: proxy
          in: path
          description: "Pharmacy path"
          required: true
          type: string
      responses:
        200:
          description: Pharmacy service response
        401:
          description: Unauthorized
        429:
          description: Too Many Requests
      x-google-api-key:
        metrics:
          - name: "pharmacy-requests"
            value: 1
        quotas:
          - metric: "pharmacy-requests"
            limits:
              - unit: "1/min"
                value: 50
    post:
      summary: Create pharmacy resource
      operationId: pharmacy_post
      parameters:
        - name: proxy
          in: path
          description: "Pharmacy path"
          required: true
          type: string
      responses:
        200:
          description: Pharmacy service response
        401:
          description: Unauthorized
        429:
          description: Too Many Requests
      x-google-api-key:
        metrics:
          - name: "pharmacy-requests"
            value: 1
        quotas:
          - metric: "pharmacy-requests"
            limits:
              - unit: "1/min"
                value: 50
  /personal-health-management/{proxy+}:
    x-google-backend:
      path_translation: APPEND_PATH_TO_ADDRESS
    get:
      summary: Get personal health data
      operationId: personalHealthManagement
      parameters:
        - name: proxy
          in: path
          description: "Personal health management path"
          required: true
          type: string
      responses:
        200:
          description: Personal health management response
        401:
          description: Unauthorized
        429:
          description: Too Many Requests
      x-google-api-key:
        metrics:
          - name: "pfm-requests"
            value: 1
        quotas:
          - metric: "pfm-requests"
            limits:
              - unit: "1/min"
                value: 20
    post:
      summary: Update personal health data
      operationId: personalHealthManagement_post
      parameters:
        - name: proxy
          in: path
          description: "Personal health management path"
          required: true
          type: string
      responses:
        200:
          description: Personal health management response
        401:
          description: Unauthorized
        429:
          description: Too Many Requests
      x-google-api-key:
        metrics:
          - name: "pfm-requests"
            value: 1
        quotas:
          - metric: "pfm-requests"
            limits:
              - unit: "1/min"
                value: 20